# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# TODO: Need to set up the base route to do persona so that links work between local and deployed instances

destination: ../_persona_site

title: Nick Pope
email: nickkpope+ghp@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A One Trick Jack of All Trades and a Master of One

host: fwnixos
baseurl: "/persona" # the subpath of your site, e.g. /blog
url: "onetrickjack.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
github_username:  nickkpope

# Build settings
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
  # - jekyll-rdf

jekyll_rdf:
  path: "_data/graph.ttl"
  language: "en"
  default_template: "rdf_index.html"
  baseiri: "https://onetrickjack.github.io/persona/"
  # restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . FILTER regex(str(?resourceUri), 'https://onetrickjack.github.io/')  }"
  # restriction: "SELECT ?resourceUri WHERE { ?resourceUri ?p ?o . }"
  class_template_mappings:
    "https://onetrickjack.github.io/persona/resume#Resume": "Resume.html"
    "http://xmlns.com/foaf/0.1/Person": "Person.html"
    "https://www.w3.org/ns/activitystreams#IntransitiveActivity": "Event.html"
  instance_template_mappings:
    "https://onetrickjack.github.io/persona/resumes/": "rdf_index.html"
  # instance_template_mappings:
  #   "https://onetrickjack.github.io/persona/resumes/NickPope_Architecture": "Resume.html"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
